# Spec file for CodeDeploy EC2 deployment.
version: 0.0
os: linux

files:
  - source: /
    destination: /tmp

hooks:
  ApplicationStart:
    - location: ./scripts/install.sh
      timeout: 300
      runas: root
