version: 0.2
env:
  git-credential-helper: yes
  variables:
    REPO_NAME: ""
    PROJECT: ""
    ART_REPO_ID: ""
    DOMAIN: ""
    BUCKET: ""

phases:
  install:
    commands:
#        - wget https://raw.githubusercontent.com/epam/aws-ci-cd-accelerator/main/modules/buckets_for_accelerator/storage_bucket_files/pack_to_deb.sh
        - aws s3 cp s3://"${BUCKET}"/pack_to_deb.sh .

  pre_build:
    commands:
        - mvn package -DskipTests=true -Dcheckstyle.skip=true
        - cp ./target/*.jar ./app.jar

  build:
    commands:
        - git describe --exact-match --tags HEAD;TAG_EXISTS=$?
        - echo $TAG_EXISTS
        - |
          if [ $TAG_EXISTS -eq 0 ]; then 
          #This condition checks the value of the TAG_EXISTS variable.
            echo "Tag for this commit not exist";
            exit 1
          else
            TAG=$(git describe --exact-match --tags HEAD);
            echo "Latest tag: $TAG"
            
            if ! echo "$TAG" | egrep -q "^v[0-9]+\.[0-9]+\.[0-9]+$"; then
              echo "Error: git tag $TAG doesn't match semver format vX.Y.Z";
              exit 1;
            fi
          fi
        - bash pack_to_deb.sh app.jar $TAG petclinic java

artifacts:
  files:
    - 'scripts/**/*'
    - '*.yml'
    - 'petclinic.deb'
  discard-paths: no
