version: 0.2
env:
  parameter-store:
    COGNITO_PASSWORD: "$COGNITO_PASSWORD_NAME"
    RP_TOKEN: "$RP_TOKEN_NAME"
  variables:
    TEST_NAME: ""
    TEST_ID: ""
    TEST_TYPE: ""
    TASK_COUNT: ""
    CONCURRENCY: ""
    RAMP_UP: ""
    HOLD_FOR: ""
    APP_TARGET_URL: ""
    COGNITO_USER: ""
    DLT_UI_URL: ""
    DLT_ALIAS: ""
    DLT_API_HOST: ""
    COGNITO_USER_POOL_ID: ""
    COGNITO_CLIENT_ID: ""
    COGNITO_IDENTITY_POOL_ID: ""
    EXPECT_SUCCESS_RATE: "95"
    SUCCESS_P95: "1"
    RP_ENDPOINT: ""
    RP_PROJECT: ""

phases:
  install:
    commands:
#      - pip3 install pytest-reportportal
      - pip3 install reportportal-client==5.3.5 -q
  build:
    commands:
      - cd ./scripts/dlt
      - python3 dlt_test.py
