version: 0.2
env:
  git-credential-helper: yes
  
phases:
  build:
    commands:
      - git describe --exact-match --tags HEAD;TAG_EXISTS=$?
      - echo $TAG_EXISTS
      - |
        if [ $TAG_EXISTS -eq 0 ]; then 
        #This condition checks the value of the TAG_EXISTS variable. If the value is 0 (meaning the tag exists)..
          echo "Tag already exists for this commit. Stop running the script."
          new_tag=$TAG_EXISTS
          echo "$new_tag" > version.txt;
          echo "TAG=$new_tag" >> env_vars.txt;
          exit 0
        else
          latest_tag=$(git describe --tags --abbrev=0 || true);
          echo $latest_tag
          if [ -z "$latest_tag" ]; then
            echo "No git tags in repository. Creating tag v0.1.0";
            latest_tag="v0.1.0";
          fi
          if ! echo "$latest_tag" | egrep -q "^v[0-9]+\.[0-9]+\.[0-9]+$"; then
            echo "Error: git tag $latest_tag doesn't match semver format vX.Y.Z";
            exit 1;
          fi

          echo "Latest tag $latest_tag";
          new_tag=$(echo "$latest_tag" | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g');
          echo "New version/tag is $new_tag";

          git tag "$new_tag";
          git push origin --tags;

          echo "$new_tag" > version.txt;
          echo "TAG=$new_tag" >> env_vars.txt;
         fi

artifacts:
  files:
    - '**/*'
    
  name: artifacts
