version: 0.2
env:
  parameter-store:
    COGNITO_PASSWORD: "$COGNITO_PASSWORD_NAME"
    RP_TOKEN: "$RP_TOKEN_NAME"
  shell: bash
  variables:
    EXPECT_SUCCESS_RATE: 95
    SUCCESS_P95: 6
    APP_TARGET_URL: ""
    COGNITO_USER: ""
    DLT_UI_URL: ""
    DLT_ALIAS: ""
    DLT_API_HOST: ""
    AWS_REGION: ""
    COGNITO_USER_POOL_ID: ""
    COGNITO_CLIENT_ID: ""
    COGNITO_IDENTITY_POOL_ID: ""
    RP_ENDPOINT: ""
    RP_PROJECT: ""
    RP_LAUNCH_NAME: " JAVA DLT TEST"
    RP_LAUNCH_DOC: "DLT Test Java Application"

phases:
  install:
    commands:
#       - pip install reportportal-client
      - pip install reportportal-client==5.2.5
  build:
    commands:
      - cd dlt
#       - python dlt_test.py
