version: 0.2
env:
  parameter-store: # it's better to use secrets manager here
    LOGIN: "$SONAR_TOKEN_NAME"
    RP_API_KEY: "$RP_TOKEN_NAME"
  variables:
    SONAR_URL: ""
    ART_REPO_ID: ""
    DOMAIN: ""
    REPO_NAME: ""
    PROJECT_KEY: ""
    ORGANIZATION: ""
    CODEBUILD_RESOLVED_SOURCE_VERSION: ""
    QG_TIMEOUT: "300"
    PR_PROVIDER: ""
    RP_ENDPOINT: ""
    RP_PROJECT: ""
    RP_LAUNCH_NAME: "JAVA SONAR TEST"
    RP_LAUNCH_DOC: "SONAR Test JAVA Application"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update
      - apt-get install -y jq
      - wget https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      - tar xzf ./*.gz
      - ln -s apache-maven-3.9.6 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip ./*.zip
      - export PATH=$PATH:/sonar-scanner-4.7.0.2747-linux/bin/
      - pip install -r scripts/sonar/requirements.txt -qq

  pre_build:
    commands:
  #
  build:
    commands:
      - cd "${CODEBUILD_SRC_DIR}"
      - |
        mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.qualitygate.wait="true" \
          -Dsonar.qualitygate.timeout=${QG_TIMEOUT} \
          -Dsonar.pullrequest.provider=${PR_PROVIDER} \
          -Dsonar.scm.revision=${CODEBUILD_RESOLVED_SOURCE_VERSION} \
          -Dsonar.organization=${ORGANIZATION} \
          -Dsonar.projectKey="${PROJECT_KEY}" \
          -Dsonar.login=${LOGIN} \
          -Dsonar.host.url=${SONAR_URL} > /dev/null

  post_build:
    commands:
#      - |
#        if [ $RP_API_KEY != '' ]; then
#        python3 -m pytest  ${CODEBUILD_SRC_DIR}/scripts/sonar/sonar_report.py \
#        -k "not quality_gate_status_check" --reportportal \
#        --tb=no --rp-launch="${REPO_NAME} SONAR" \
#        --rp-launch-description="${REPO_NAME} SONAR: ${SONAR_URL}/summary/new_code?id=${PROJECT_KEY}"
#        fi
      - python3 ${CODEBUILD_SRC_DIR}/scripts/sonar/sonar_report.py --status-check



artifacts:
  files:
    - '**/*'
