version: 0.2
env:
  variables:
    REPO_NAME: ""
    PROJECT: ""
    ART_REPO_ID: ""
    DOMAIN: ""
    BUCKET: ""

phases:

  build:
    commands:
        - mvn clean package

  post_build:
    commands:
        - wget -P target https://raw.githubusercontent.com/epam/aws-ci-cd-accelerator/main/modules/buckets_for_accelerator/storage_bucket_files/pack_to_deb.sh
        - cd ./target
        - bash pack_to_deb.sh spring-petclinic-3.2.0.jar 3.2.0 petclinic java

artifacts:
  files:
    - 'scripts/*'
    - '*.yml'
    - 'target/petclinic.deb'
  discard-paths: yes
