version: 0.2
env:
  parameter-store:
    OPENAI_TOKEN: "$OPENAI_TOKEN_NAME"
    GITHUB_TOKEN: "$GITHUB_TOKEN_NAME"
  variables:
    LLM_MODEL: ""
    OPENAI_API_ENDPOINT: ""
phases:
  install:
    commands:
      - git checkout ${SOURCE_BRANCH}
      - pip install -r ${CODEBUILD_SRC_DIR}/scripts/ai/requirements.txt -qq

  build:
    commands:
      - python ${CODEBUILD_SRC_DIR}/scripts/ai/ai_cicd_analyzer.py
