version: 0.2
env:
  variables:
    REPO_NAME: ""
    PROJECT: ""
    ART_REPO_ID: ""
    DOMAIN: ""
    BUCKET: ""

phases:

  build:
    commands:
        - mvn package -DskipTests=true -Dcheckstyle.skip=true
        - cp ./target/*.jar ./app.jar

  post_build:
    commands:
#        - wget -P target https://raw.githubusercontent.com/epam/aws-ci-cd-accelerator/main/modules/buckets_for_accelerator/storage_bucket_files/pack_to_deb.sh
        - aws s3 cp s3://"${BUCKET}"/pack_to_deb.sh .
#        - cd ./target
        - ls -la
        - bash pack_to_deb.sh app.jar 3.2.0 petclinic java

artifacts:
  files:
    - 'scripts/**/*'
    - '*.yml'
    - 'petclinic.deb'
  discard-paths: no
